FROM golang AS compiling_stage
WORKDIR /go/src/APIGateway/API_gateway
COPY . /go/src/APIGateway/API_gateway/
RUN go mod init
RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o gw .

FROM alpine:latest
WORKDIR /root/
COPY --from=compiling_stage /go/src/APIGateway/API_gateway .
ENTRYPOINT ./gw