FROM golang AS compiling_stage
WORKDIR /go/src/APIGateway/NewsAggregator
COPY . /go/src/APIGateway/NewsAggregator/
RUN go mod init
RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o news .

FROM alpine:latest
WORKDIR /root/
COPY --from=compiling_stage /go/src/APIGateway/NewsAggregator .
ENTRYPOINT ./news