FROM golang AS compiling_stage
WORKDIR /go/src/APIGateway/Comments
COPY . /go/src/APIGateway/Comments/
RUN go mod init
RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o comments .

FROM alpine:latest
WORKDIR /root/
COPY --from=compiling_stage /go/src/APIGateway/Comments .
ENTRYPOINT ./comments